<a href="https://colab.research.google.com/github/sisi-y/100-Days-ML-Journey/blob/main/Day_2_Classification_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("=" * 60)
print("📚 DAY 1 REVIEW")
print("=" * 60)
print()
print("Yesterday I learned:")
print()
print("1️⃣ REGRESSION - Predicting NUMBERS")
print("   Example: Predict house price (a number!)")
print("   Input: House size (100m)")
print("   Output: Price (Kshs 4,000,000) ← a NUMBER")
print()
print("2️⃣ The ML Process:")
print("   • Get data → Prepare → Train → Predict → Evaluate")
print()
print("3️⃣ I built a model that predicts house prices!")
print("   It LEARNED from examples!")
print("   It can predict prices for NEW houses!")
print()
print("=" * 60)
print()
print("TODAY: We're learning CLASSIFICATION!")
print("Instead of predicting numbers, we make CHOICES!")
print()
print("=" * 60)

📚 DAY 1 REVIEW

Yesterday I learned:

1️⃣ REGRESSION - Predicting NUMBERS
   Example: Predict house price (a number!)
   Input: House size (100m)
   Output: Price (Kshs 4,000,000) ← a NUMBER

2️⃣ The ML Process:
   • Get data → Prepare → Train → Predict → Evaluate

3️⃣ I built a model that predicts house prices!
   It LEARNED from examples!
   It can predict prices for NEW houses!


TODAY: We're learning CLASSIFICATION!
Instead of predicting numbers, we make CHOICES!



In [ ]:
print("REGRESSION vs CLASSIFICATION")
print("=" * 60)
print()

print("REGRESSION (Predicting Numbers):")
print("-" * 60)
print("Question                           Answer (NUMBER)")
print("What will the house price be?        Kshs 4,500,000")
print("How old is this person?           32 years")
print("What's the temperature?           28 degrees")
print("How many likes will post get?     1,247 likes")
print()

print("CLASSIFICATION (Making Choices):")
print("─" * 60)
print("Question                          Answer (CATEGORY)")
print("─" * 60)
print("Is this email spam?               YES or NO")
print("Is customer happy or sad?         HAPPY or SAD")
print("Is this fruit apple or orange?    APPLE or ORANGE")
print("Will patient be sick or healthy?  SICK or HEALTHY")
print()

print("=" * 60)
print()
print("Key difference:")
print("REGRESSION → Predicts exact numbers (1, 2, 3.5, 100, etc.)")
print("CLASSIFICATION → Chooses categories (Yes/No, Cat/Dog, etc.)")
print()
print("=" * 60)

REGRESSION vs CLASSIFICATION

REGRESSION (Predicting Numbers):
------------------------------------------------------------
Question                           Answer (NUMBER)
What will the house price be?        Kshs 4,500,000
How old is this person?           32 years
What's the temperature?           28 degrees
How many likes will post get?     1,247 likes

CLASSIFICATION (Making Choices):
────────────────────────────────────────────────────────────
Question                          Answer (CATEGORY)
────────────────────────────────────────────────────────────
Is this email spam?               YES or NO
Is customer happy or sad?         HAPPY or SAD
Is this fruit apple or orange?    APPLE or ORANGE
Will patient be sick or healthy?  SICK or HEALTHY


Key difference:
REGRESSION → Predicts exact numbers (1, 2, 3.5, 100, etc.)
CLASSIFICATION → Chooses categories (Yes/No, Cat/Dog, etc.)



In [ ]:
print("🌍 CLASSIFICATION IN THE REAL WORLD")
print("=" * 60)
print()

print("1. HEALTHCARE 🏥")
print("   Question: Does patient have disease?")
print("   Categories: SICK or HEALTHY")
print("   ML looks at: symptoms, age, test results")
print("   ML decides: Which category patient belongs to")
print()

print("2. EMAIL 📧")
print("   Question: Is this email spam?")
print("   Categories: SPAM or NOT SPAM")
print("   ML looks at: words, sender, links")
print("   ML decides: Spam folder or inbox?")
print()

print("3. BANKING 💳")
print("   Question: Is this transaction fraud?")
print("   Categories: FRAUD or LEGITIMATE")
print("   ML looks at: amount, location, time, pattern")
print("   ML decides: Block card or allow transaction?")
print()

print("4. FACE RECOGNITION 📱")
print("   Question: Is this Sarah or not Sarah?")
print("   Categories: SARAH or NOT SARAH")
print("   ML looks at: facial features")
print("   ML decides: Unlock phone or don't unlock?")
print()

print("5. AGRICULTURE 🌾")
print("   Question: Is this plant healthy or diseased?")
print("   Categories: HEALTHY or DISEASED")
print("   ML looks at: leaf color, spots, shape")
print("   ML decides: Which category plant belongs to")
print()

print("=" * 60)
print()
print("Today we'll build our own classification model!")
print("We'll teach ML to make choices, just like these examples!")
print()

🌍 CLASSIFICATION IN THE REAL WORLD

1. HEALTHCARE 🏥
   Question: Does patient have disease?
   Categories: SICK or HEALTHY
   ML looks at: symptoms, age, test results
   ML decides: Which category patient belongs to

2. EMAIL 📧
   Question: Is this email spam?
   Categories: SPAM or NOT SPAM
   ML looks at: words, sender, links
   ML decides: Spam folder or inbox?

3. BANKING 💳
   Question: Is this transaction fraud?
   Categories: FRAUD or LEGITIMATE
   ML looks at: amount, location, time, pattern
   ML decides: Block card or allow transaction?

4. FACE RECOGNITION 📱
   Question: Is this Sarah or not Sarah?
   Categories: SARAH or NOT SARAH
   ML looks at: facial features
   ML decides: Unlock phone or don't unlock?

5. AGRICULTURE 🌾
   Question: Is this plant healthy or diseased?
   Categories: HEALTHY or DISEASED
   ML looks at: leaf color, spots, shape
   ML decides: Which category plant belongs to


Today we'll build our own classification model!
We'll teach ML to make choices, ju

In [ ]:
print("=" * 60)
print("📚 TODAY'S PROJECT: PASS/FAIL PREDICTOR")
print("=" * 60)
print()

print("THE SCENARIO:")
print("─" * 60)
print("You're a teacher with 10 students.")
print("They've all taken the exam.")
print("You know:")
print("  • How many hours each studied")
print("  • Their previous exam score")
print("  • Their attendance percentage")
print()
print("You also know:")
print("  • Who PASSED (scored 50% or more)")
print("  • Who FAILED (scored less than 50%)")
print()

print("THE GOAL:")
print("─" * 60)
print("Teach ML to predict PASS or FAIL for NEW students!")
print()
print("Example prediction:")
print("  Input: Student studied 8 hours, scored 75% before, 90% attendance")
print("  ML predicts: This student will PASS! ✅")
print()
print("  Input: Student studied 2 hours, scored 40% before, 60% attendance")
print("  ML predicts: This student will FAIL! ❌")
print()

print("=" * 60)
print()
print("Let's build it! 🚀")
print()
print("=" * 60)

📚 TODAY'S PROJECT: PASS/FAIL PREDICTOR

THE SCENARIO:
────────────────────────────────────────────────────────────
You're a teacher with 10 students.
They've all taken the exam.
You know:
  • How many hours each studied
  • Their previous exam score
  • Their attendance percentage

You also know:
  • Who PASSED (scored 50% or more)
  • Who FAILED (scored less than 50%)

THE GOAL:
────────────────────────────────────────────────────────────
Teach ML to predict PASS or FAIL for NEW students!

Example prediction:
  Input: Student studied 8 hours, scored 75% before, 90% attendance
  ML predicts: This student will PASS! ✅

  Input: Student studied 2 hours, scored 40% before, 60% attendance
  ML predicts: This student will FAIL! ❌


Let's build it! 🚀



In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

print("Libraries imported!")

Libraries imported!


In [ ]:
students = ["Alice", "Bob", "Charlie", "Diana", "Eve",
            "Frank", "Grace", "Henry", "Iris", "Jack"]
study_hours = [8, 4, 6, 2, 7, 3, 9, 5, 1, 6]      # Hours studied
previous_score = [75, 55, 68, 45, 80, 50, 85, 60, 40, 70]  # Previous exam %
attendance = [90, 70, 85, 60, 95, 65, 98, 75, 55, 88]
results = [1, 1, 1, 0, 1, 0, 1, 1, 0, 1]

print("OUR STUDENT DATA:")
print("=" * 80)
print(f"{'Student':<10} {'Study Hrs':<12}{'Previous Score':<12} {'Attendance':<12}")
print("=" * 80)

for i in range(len(students)):
    result_text = "✅ PASSED" if results[i] == 1 else "❌ FAILED"
    print(f"{students[i]:<10} {study_hours[i]:<12} {previous_score[i]:<12} {attendance[i]:<12} {result_text:<10}")

print("=" * 80)
print()
print(f"Total students: {len(students)}")
print(f"Passed: {sum(results)} students")
print(f"Failed: {len(results) - sum(results)} students")

OUR STUDENT DATA:
Student    Study Hrs   Previous Score Attendance  
Alice      8            75           90           ✅ PASSED  
Bob        4            55           70           ✅ PASSED  
Charlie    6            68           85           ✅ PASSED  
Diana      2            45           60           ❌ FAILED  
Eve        7            80           95           ✅ PASSED  
Frank      3            50           65           ❌ FAILED  
Grace      9            85           98           ✅ PASSED  
Henry      5            60           75           ✅ PASSED  
Iris       1            40           55           ❌ FAILED  
Jack       6            70           88           ✅ PASSED  

Total students: 10
Passed: 7 students
Failed: 3 students


In [ ]:
X = np.array([study_hours, previous_score, attendance])
X = X.T
print("INPUT DATA (X):")
print("=" * 60)
print("Each row = one student")
print("Each column = one piece of information")
print()
print(X)
print()
print(f"Shape: {X.shape}")
print(f"That means: {X.shape[0]} students, {X.shape[1]} features")
print()

y = np.array(results)

print("OUTPUT DATA (y):")
print("=" * 60)
print("1 = Passed, 0 = Failed")
print()
print(y)
print()
print(f"Shape: {y.shape}")
print(f"That means: {y.shape[0]} results (one per student)")

INPUT DATA (X):
Each row = one student
Each column = one piece of information

[[ 8 75 90]
 [ 4 55 70]
 [ 6 68 85]
 [ 2 45 60]
 [ 7 80 95]
 [ 3 50 65]
 [ 9 85 98]
 [ 5 60 75]
 [ 1 40 55]
 [ 6 70 88]]

Shape: (10, 3)
That means: 10 students, 3 features

OUTPUT DATA (y):
1 = Passed, 0 = Failed

[1 1 1 0 1 0 1 1 0 1]

Shape: (10,)
That means: 10 results (one per student)


In [1]:
print("Helloo, AI World!")
print("My name is Wangari")
print("Today I begin my journey to master AI/ML")

hours_per_day = 6
days_in_11_months = 330
total_hours = hours_per_day * days_in_11_months


print(f"\nIn 11 months, I will invest {total_hours} hours learning AI")
print(f"That's equivalent to {total_hours / 40} weeks of full-time work!")

def calculate_learning_progress(days_completed):
    total_days = 330
    percentage = (days_completed /total_days) * 100
    print(f"Progree'; {percentage:.1f}% complete")
    print(f"Days Remaining: {total_days - days_completed}")
    print("\n--- My Progress Tracker ---")
calculate_learning_progress(1)

Helloo, AI World!
My name is Wangari
Today I begin my journey to master AI/ML

In 11 months, I will invest 1980 hours learning AI
That's equivalent to 49.5 weeks of full-time work!
Progree'; 0.3% complete
Days Remaining: 329

--- My Progress Tracker ---


In [2]:
name = "Wangari"
goal = "Master AI and ML"
favorite_ai_tool = "ChatGPT"
print("=== MY AI JOURNEY ===")
print(f"I'm {name}")
print(f"My goal: {goal}")
print(f"Favorite AI tool: {favorite_ai_tool}")

age = 31
days_into_journey = 2
hours_studied_today = 6
total_project_goals = 15

total_hours = days_into_journey * 3
hours_remaining = (330 * 3) - total_hours
project_per_month = total_project_goals / 11

has_python_installed = True
has_ai_job = False
is_commited = True

print(f"\n=== STATUS ===")
print(f"python_installed: {has_python_installed}")
print(f"ai_job_secured: {has_ai_job}")
print(f"commited_to_learning: {is_commited}")

skills_to_learn = "python", "Machine_Learning", "AI", "NL"
Resources = ["fast.ai", "kaggle", "Google_Colab", "Github"]
projects_completed = ["Hello World!"]

print(f"\n=== MY LEARNING PATH ===")
print(f"Skills to master: {skills_to_learn}")
print(f"Number of skills: {len(skills_to_learn)}")
print(f"First skill: {skills_to_learn[0]}")
print(f"Last skill: {skills_to_learn[-1]}")

my_progress = {
    "days_completed": 2,
    "programs_written": 2,
    "github_repos": 1,
    "linkedin_posts": 1,
    "confidence_level": "Growing"
}

int(f"\n=== PROGRESS TRACKER ===")
for key, value in my_progress.items():
    print(f"{key}: {value}")

programs_per_day = my_progress["progress_written"] / my_progress


=== MY AI JOURNEY ===
I'm Wangari
My goal: Master AI and ML
Favorite AI tool: ChatGPT

=== STATUS ===
python_installed: True
ai_job_secured: False


In [10]:
print("=== AI PATH ANALYZER ===\n")
hours_available_daily = 6
has_python_knowledge = "true"
days_studied = 2

if hours_available_daily >=6:
    print("FAST TRACK: You can progress rapidly!")
    recommended_completion = "8-10 months"
elif hours_available_daily >= 3:
    print("STEADY PACE YOU ARE ON TRACK!")
    recommended_completion = "11 months"
else:
    print ("EXTENDED TIMELINE: Consider increasing study time")
    recommended_completion = "14-18 months"

print(f"estimated completion: {recommended_completion}\n")

# Corrected: has_python_knowledge should be checked for its boolean value or a specific string
if has_python_knowledge == "true": # Assuming "true" means True
  if days_studied < 7:
    print("Status: Ready to start ML concepts")
else:
    print("Status: Focus on Python Basics first")


print("\n=== 11 MONTH ROADMAP ===\n")
months = ["Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
Focus_areas = [
    "Python & Math Foundations",
    "ML Basics & First Projects",
    "Deep Learning & Neural Networks",
    "NLP & LLMs",
    "Advanced Projects & Portfolio",
    "Specialization Deep Dive",
    "MLOps & Production",
    "Advanced Topics & Teaching",
    "Real-world Experience",
    "Interview Prep",
    "Job Search & Networking"
]

for i in range(len(months)):
    # Corrected: Referencing Focus_areas list correctly
    print(f"Month {i+1} ({months[i]}): {Focus_areas[i]}")

print("\n=== COUNTDOWN TO MASTERY ===\n")

days_remaining = 328
milestones = [300, 250, 200, 150, 50, 30, 7, 1]

for milestone in milestones:
  if days_remaining >= milestone:
    print(f"milestone: {milestone} days to go!")

print("\n=== SKILL LEVEL CALCULATOR ===\n")

def calculate_skill_level(days_studied, hours_per_day, projects_completed):
  total_hours = days_studied * hours_per_day
  # Corrected: Assignment operator '=' instead of comparison '=='
  skill_score = total_hours + (projects_completed * 10)

  # Corrected: Referencing variable 'skill_score' instead of string literal
  if skill_score < 50:
        level = "Beginner"
        next_goal = "Complete 5 more projects"
  elif skill_score < 200:
        level = "Learning"
        next_goal = "Build a portfolio piece"
  elif skill_score < 500:
        level = "Intermediate"
        next_goal = "Contribute to open source"
  else:
        level = "Advanced"
        next_goal = "Apply for AI roles"

  # Corrected: Return the actual variables
  return level, next_goal, skill_score

# Corrected: Fix typos in parameter names
my_level, my_next_goal, my_score = calculate_skill_level(
    days_studied=2,
    hours_per_day=6, # Assuming hours_available_daily is intended here
    projects_completed=1
    )

print(f"Your skill score: {my_score}")
print(f"current level: {my_level}")
print(f"Next goal: {my_next_goal}")

print("\n=== MY DAILY LOG ===\n")
daily_log = {
    "Day1": {
        "hours": 3,
        "topics": ["Variables", "Control Flow Started"],
        "feeling": "Determined"
    },
    "Day 2": {
        "hours": 2,
        "topics": ["Variables", "Control Flow Started"],
        "feeling": "Determined"
    }
}

for day, data in daily_log.items():
    print(f"{day}:")
    print(f"  ⏱️  Hours: {data['hours']}")
    print(f"  📚 Topics: {', '.join(data['topics'])}")
    print(f"  😊 Feeling: {data['feeling']}")
    print()


total_hours_so_far = sum(day["hours"] for day in daily_log.values())
print(f"Total hours invested: {total_hours_so_far}")
print(f"Average hours per day: {total_hours_so_far / len(daily_log):.1f}")

# Motivational message
print(f"\n🔥 You've already invested {total_hours_so_far} hours!")
print("Every hour brings you closer to mastery. Keep going! 🚀")


=== AI PATH ANALYZER ===

FAST TRACK: You can progress rapidly!
estimated completion: 8-10 months

Status: Ready to start ML concepts

=== 11 MONTH ROADMAP ===

Month 1 (Feb): Python & Math Foundations
Month 2 (Mar): ML Basics & First Projects
Month 3 (Apr): Deep Learning & Neural Networks
Month 4 (May): NLP & LLMs
Month 5 (Jun): Advanced Projects & Portfolio
Month 6 (Jul): Specialization Deep Dive
Month 7 (Aug): MLOps & Production
Month 8 (Sep): Advanced Topics & Teaching
Month 9 (Oct): Real-world Experience
Month 10 (Nov): Interview Prep
Month 11 (Dec): Job Search & Networking

=== COUNTDOWN TO MASTERY ===

milestone: 300 days to go!
milestone: 250 days to go!
milestone: 200 days to go!
milestone: 150 days to go!
milestone: 50 days to go!
milestone: 30 days to go!
milestone: 7 days to go!
milestone: 1 days to go!

=== SKILL LEVEL CALCULATOR ===

Your skill score: 22
current level: Beginner
Next goal: Complete 5 more projects

=== MY DAILY LOG ===

Day1:
  ⏱️  Hours: 3
  📚 Topics: Var